image: docker:latest

services:
  - docker:dind

stages:
  - install
  - pre_build
  - build
  - deploy

variables:
  IMAGE_TAG: "${CI_COMMIT_TIMESTAMP}"
  ECR_REGISTRY: "493512622090.dkr.ecr.ap-southeast-1.amazonaws.com"
  EKS_CLUSTER: "visitor-dev"
  AWS_REGION: "ap-southeast-1"

before_script:
  - apk add --no-cache curl unzip bash sed python3 py3-pip py3-virtualenv
  - python3 -m venv /tmp/awscli-venv
  - . /tmp/awscli-venv/bin/activate
  - pip install awscli
  - aws --version
  - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
  - chmod +x kubectl && mv kubectl /usr/local/bin/
  - curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

install:
  stage: install
  script:
    - echo "✅ Tools installed"
    - kubectl version --client
    - docker-compose version

before_script:
  - apk add --no-cache curl unzip bash sed python3 py3-pip py3-virtualenv
  - python3 -m venv /tmp/awscli-venv
  - . /tmp/awscli-venv/bin/activate
  - pip install awscli
  - export AWS_REGION="ap-southeast-1"
  - export AWS_DEFAULT_REGION="ap-southeast-1"
  - aws configure set region $AWS_REGION
  - aws --version
  - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
  - chmod +x kubectl && mv kubectl /usr/local/bin/
  - curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

pre_build:
  stage: pre_build
  script:
    - echo "🔐 Logging into ECR"
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - echo "🔍 Verifying AWS identity"
    - aws sts get-caller-identity
    - echo "🔧 Updating kubeconfig"
    - aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION
deploy:
  stage: deploy
  script:
    - echo "🚀 Deploying to EKS"
    - aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION
    - kubectl get nodes
    - sed -i "s|<your-registry>/visitor-counter-app:latest|$ECR_REGISTRY/visitor-counter-app:$IMAGE_TAG|g" k8s/deployment.yaml
    - kubectl apply -f k8s/
#  when: manual
  allow_failure: false

