version: '3.8'

services:
  visitor-counter-app:
    build:
      context: .
    image: visitor-counter-app:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
